language: objective-c
osx_image: xcode8
env:
  global:
    - PROJECT=Tests/CoreDataDandyTests.xcodeproj
    - SCHEME=CoreDataDandyTests
    - DESTINATION="OS=10.0,name=iPhone 7"
script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -sdk iphonesimulator test